name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: cargo build --release --verbose
      
    - name: Run tests
      run: cargo test --release --verbose

    - name: Compress
      run: cd target/release && tar -czf resfetch-mac.tar.gz resfetch

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/resfetch-mac.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
